# Parameter Constants

# Configure base settings
PARAM_MAX_MOVING_GATE = "0000"
PARAM_MAX_STATIC_GATE = "0100"
PARAM_EMPTY_DURATION = "0200"
# Configure individual gates
PARAM_GATE_SELECT = "0000"
PARAM_MOVING_GATE_WORD = "0100"
PARAM_STATIC_GATE_WORD = "0200"
# Special case
PARAM_SELECT_ALL_GATE = "FFFF"

# Validation Constants
GATE_MIN = 0
GATE_MAX = 8
TIMEOUT_MIN = 0
TIMEOUT_MAX = 65535
SENS_MIN = 0
SENS_MAX = 100

# Read Parameter Indices
REF_MAX_MOVING_GATE = 12
REF_MAX_STATIC_GATE = 13

REF_MOVING_GATE_SENS_0 = 14
REF_MOVING_GATE_SENS_1 = 15
REF_MOVING_GATE_SENS_2 = 16
REF_MOVING_GATE_SENS_3 = 17
REF_MOVING_GATE_SENS_4 = 18
REF_MOVING_GATE_SENS_5 = 19
REF_MOVING_GATE_SENS_6 = 20
REF_MOVING_GATE_SENS_7 = 21
REF_MOVING_GATE_SENS_8 = 22

REF_STATIC_GATE_SENS_0 = 23
REF_STATIC_GATE_SENS_1 = 24
REF_STATIC_GATE_SENS_2 = 25
REF_STATIC_GATE_SENS_3 = 26
REF_STATIC_GATE_SENS_4 = 27
REF_STATIC_GATE_SENS_5 = 28
REF_STATIC_GATE_SENS_6 = 29
REF_STATIC_GATE_SENS_7 = 30
REF_STATIC_GATE_SENS_8 = 31


REF_TARGET_TYPE = 4

REF_TARGET_LOOKUP = {0: "No Target",
                     1: "Moving Target",
                     2: "Static Target",
                     3: "Moving + Static Target"}

REF_TARGET_MOVE_DIST_HEAD = 5
REF_TARGET_MOVE_DIST_TAIL = 6
REF_TARGET_MOVE_ENERGY = 7
REF_TARGET_STATIC_DIST_HEAD = 8
REF_TARGET_STATIC_DIST_TAIL = 9
REF_TARGET_STATIC_ENERGY = 10
REF_DETECT_DIST = 11

# Cut out 1-7 for brevity
REF_MOVING_GATE_ENERGY_0 = 14
REF_MOVING_GATE_ENERGY_8 = 23

REF_STATIC_GATE_ENERGY_0 = 24
REF_STATIC_GATE_ENERGY_8 = 33

REF_RADAR_POLING_RATE = 10 # Radar updates at 10Hz
